### ISSUE TITLE
Correlation between simulated and actual data

### ISSUE THREAD

**Issue by Rohan2821999** [Rohan2821999/MathCog_Modelling#2]
@cbattista  Below is the graph for the correlation between actual easiness vals and simulated vals over all the points.  Looks pretty bad :( 

![fig](https://cloud.githubusercontent.com/assets/13100688/17869396/f7749f1e-6867-11e6-8dc5-234b8a2e0472.JPG)

Here is what weber fraction, m, intercept values I have used for the ages : 

```
if (18 >= age_grade >= 15):
            Child = Person(0.16,-16,650)
elif(14 >= age_grade >= 11 ):
            Child = Person(0.22,-25,750)
elif(10 >= age_grade >= 8):
            Child = Person(0.25,-30,900)
elif(age_grade == 7):
            Child = Person(0.27,-32,1000)
# where age_grade is the age of the person
```

**Comment by Rohan2821999** [comment]
And the Pearson Coefficient Matrix is 

```
[[ 1. 0       0.01059]
[0.01059       1.0]]
```

So the correlation is almost 0

**Comment by cbattista** [comment]
Well it looks like it works pretty well (top right cluster) for some and
not for others (the rest of it).

So now, we can think about why that would be...firstly, I realized I didn't
pull out the 'practice' trials out of the data so that might have something
to do with it...so that's one thing.  But it's kind of interesting to see
that there seem to be 'categories' there...

So one thing we want to ask is, do we have 'types' of people, where it fits
for some and not for others?  Or, is it just a huge mess?

**Comment by Rohan2821999** [comment]
Checked that.. all the 4 clusters exist and are quite prominent in all 'types' of people. So the clusters are not independent to 'categories' or 'types' of people.

**Comment by cbattista** [comment]
Ok, good to know.  So now let me see about removing all those practice
trials...

**Comment by Rohan2821999** [comment]
NDE Graph of Simulated Easiness Values vs Actual Easiness Values for all correct trials:

![image](https://cloud.githubusercontent.com/assets/13100688/17910744/1a26f598-693f-11e6-91bb-8468097d3cc3.png)

Following slope and intercept values were used for different age ranges:

```
Age 15-18: slope = -16, intercept = 750
Age 11-14: slope = -30, intercept = 950
Age 10-8: slope = -40, intercept = 1200
Age 7: slope = -50, intercept = 1500
```

**Comment by cbattista** [comment]
Hmm quite a blob we have there...

A few questions:

Can you just plot RTs (instead of easiness)
Can you color code the different age ranges - curious to see whether data
fits better for any of the age ranges...
What's up with the 'stripe' pattern in the simulated data?

**Comment by Rohan2821999** [comment]
Sure,So you want a graph of the Simulated RT's vs Actual RT's color coded according to ages, right? Or do you want  a graph of simulated RT's vs distance (color coded)?

Not surely about the stripe pattern, would look into it..

**Comment by cbattista** [comment]
Yes, simulated RTs vs actual RTs color coded according to ages.
for example...
Age 15-18: black
Age 11-14: blue
Age 10-8: green
Age 7: red

**Comment by Rohan2821999** [comment]
Here is the graph:

![image](https://cloud.githubusercontent.com/assets/13100688/17913326/028262f6-694e-11e6-9492-7bd5da56de57.png)

Age 15-18: red
Age 11-14: blue
Age 8-10:  green
Age 7: brown

**Comment by cbattista** [comment]
So for the 7 year-olds there might be a bit of a (weak) relationship there but the rest is indeed quite bad....definitely need a better model!

**Comment by Rohan2821999** [comment]
I have added two graphs (Actual RT vs Ratios and Sim_RT vs Ratios) ::: Red - Acc = 0 , Green - Acc = 1

![image](https://cloud.githubusercontent.com/assets/13100688/17986581/3f310210-6ad0-11e6-9cb9-5a3b419f2f64.png)

![image](https://cloud.githubusercontent.com/assets/13100688/17986660/a8d7f642-6ad0-11e6-884a-fcff50518b10.png)

**Comment by cbattista** [comment]
neat - can you make the circles more transparent (using the 'alpha'
argument in the scatter function) it will make things easier to see...

**Comment by Rohan2821999** [comment]
![image](https://cloud.githubusercontent.com/assets/13100688/17986968/3baac0e8-6ad2-11e6-90b0-9a0601159043.png)

![image](https://cloud.githubusercontent.com/assets/13100688/17987005/795efdbe-6ad2-11e6-9917-5faf8f7ea1aa.png)

**Comment by Rohan2821999** [comment]
Graph of Avg_RT Values (Actual) vs Avg Accuracy values for each subject:

![image](https://cloud.githubusercontent.com/assets/13100688/17994112/cab2e594-6b0a-11e6-9378-913675e097fa.png)

Doesn't quite look as expected..

**Comment by Rohan2821999** [comment]
Plot of Simulated RT (sampled from normal distribution with std = intercept) vs Ratios. The plot more or less matches the Actual RT vs Ratio scatter plot..

![image](https://cloud.githubusercontent.com/assets/13100688/18017584/f821bf92-6b86-11e6-9461-10ebbd3949c2.png)

Should I re-plot my easiness values graph now (probably could get better results)?

**Comment by cbattista** [comment]
yeah, let's try that...

**Comment by Rohan2821999** [comment]
RT Histogram Chart

![image](https://cloud.githubusercontent.com/assets/13100688/18021413/1eedc7aa-6b9c-11e6-893f-bb07a8a918bf.png)

**Comment by Rohan2821999** [comment]
Histogram Plot for Simulated and Actual E

![image](https://cloud.githubusercontent.com/assets/13100688/18021834/fa1a079c-6b9e-11e6-9e9d-f13f7bd7c1b6.png)

**Comment by Rohan2821999** [comment]
for w = 0.17

![image](https://cloud.githubusercontent.com/assets/13100688/18022129/38677118-6ba1-11e6-8b8b-e6b6fafa1022.png)

**Comment by Rohan2821999** [comment]
Kinda weird still overestimating difficulty a bit at a pretty low w..

**Comment by cbattista** [comment]
huh, I guess it's the NDE driving the RT there then...
